### PR TITLE
Custom Resources in Root orchestrator

### PR DESCRIPTION
**Pull request by melkodary**
#321 

### How to use
1. create a custom resource which accepts an openapiv3 schema, e.g:
```json
{
    "resource_type": "employees",
    "schema":
    {
        "type": "object",
        "properties":
        {
            "age":
            {
                "type": "integer"
            },
            "address":
            {
                "type": "string"
            },
            "skills":
            {
                "type": "array",
                "items":
                {
                    "type": "string"
                }
            },
            "languages":
            {
                "type": "array",
                "items":
                {
                    "type": "string"
                }
            },
            "name":
            {
                "type": "string"
            },
            "email":
            {
                "type": "string"
            }
        }
    }
}
```
2. Now that a custom resource is created, you should notice that the under the custom_resources database there is new collection with the name `employees`. This also creates a new endpoint, `/api/v1/custom-resources/employees`. With the endpoints and storage ready, you can use RESTful api to manage the new entity.

### Future Work:
- Add new attribute to the schema called `plural_name` to enforce endpoints to always be in the form of `/api/v1/{plural_name}` thus following proper convention of naming uri.

### CODE REVIEW

**Review by giobart — CHANGES_REQUESTED** [review]
Tested this branch and it looks like it introduces a regression in the front-end side, likely caused by slightly different objects returned by the API. 
It looks like service statuses and logs might have changed and the FE is not able to retrieve them. 

Screenshot 2024-07-29 at 13 40 21
Screenshot 2024-07-29 at 13 40 26

**Comment by oakestra-admin** [comment]
🥀 This PR is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 10 days.

**Comment by melkodary** [comment]
error is rooted in hooks branch, now fixed.

**Review by giobart — APPROVED** [review]
image


Tested and it works. I created an employee custom resoruce like the example you provided and it worked fine.

**Pull request merged**
