### PR TITLE
Add privileged-containers/services & HTTP registry support

### PR DESCRIPTION
**Pull request by Malyuk-A**
## Context
This PR is part of the migration efforts for the main OAK repo changes I performed to get the FLOps Addon working.

This PR adds the new privileged attribute to services that enable special privileges for running the containerd containers. 

This is necessary e.g. when trying to build images in those services (e.g. via [buildah](https://buildah.io/)).

Additionally, this PR also adds support to pull images from HTTP registries instead of HTTPS-only ones.
(This is necessary to be able to pull images from the custom FLOps addon image registry which for now uses HTTP)

### CODE REVIEW

**Comment by Malyuk-A** [comment]
@giobart
I fixed the new linting issues and added the Readme change

**Comment by oakestra-admin** [comment]
🥀 This PR is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 10 days.

**Comment by oakestra-admin** [comment]
🥀 This PR is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 10 days.

**Review by giobart — APPROVED** [review]

**Comment by Malyuk-A** [comment]
I just tested the changes again on the latest develop branch state and things still work.

**Pull request merged**
