### PR TITLE
Add mosquitto broker auth to cluster manager and node engine

### LINKED ISSUE #357: Add Mosquitto Broker Auth
## Short
Add the possibility of performing Mosquitto authentication.

## Proposal
Currently, mosquito auth has been turned off. We can use env variables at the Cluster Level and flags at the Node to enable certificate-based authentication.

After [generating the certificates](https://mosquitto.org/man/mosquitto-tls-7.html) its possible to set in [mosquitto.conf](https://mosquitto.org/man/mosquitto-conf-5.html) the following settings:
- require_certificate
- use_identity_as_username

This will enable the clients to authenticate using the certificates. Note that according to the docs, no password is required for this authorization method.

Tasks to solve this issue:

- [x] Create a compose override for the cluster manager (both 1DOC and cluster orch compose file) that mounts the folder `~/oakestra/certs` to `/certs` on (i)cluster manager (ii) mosquitto and (iii) service manager containers. The override also sets the ENV variable MQTT_CERT to `/certs` for the cluster manager and service manager. 
- [x] Modify the cluster manager [mqtt init](https://github.com/oakestra/oakestra/blob/3e0b988c3ad09e8b306b9eecc2eff1c4b3716785/cluster_orchestrator/cluster-manager/mqtt_client.py#L79) to use certificate based auth if MQTT_CERT  is not empty
- [x] Add documentation [here](https://github.com/oakestra/oakestra/blob/develop/cluster_orchestrator/README.md) on how to configure [mosquitto.conf](https://github.com/oakestra/oakestra/tree/develop/cluster_orchestrator/mosquitto) to get cert-based auth. 
- [x] Add NodeEngine [flag](https://github.com/oakestra/oakestra/blob/3e0b988c3ad09e8b306b9eecc2eff1c4b3716785/go_node_engine/cmd/root.go#L44) to accept MQTT certificate path for [mosquitto auth](https://github.com/oakestra/oakestra/blob/3e0b988c3ad09e8b306b9eecc2eff1c4b3716785/go_node_engine/mqtt/MqttClient.go#L74) 

## Ratio
For deployments where cluster and workers are not in the same private network, this is a must.

## Impact
Cluster orchestrator, Node Engine, and Net Manager

## Development time
1/2 Weeks

## Status
Discussed

## Checklist
 
- [x] Discussed
- [ ] Documented
- [ ] Implemented
- [ ] Tested

### PR DESCRIPTION
**Pull request by Mjaethers**
Fixes #357.

By using the override-mosquitto-auth.yml docker override the cluster orchestrator can be started in a manner such that MQTT communications are sent via TLS. To this effect the mosquitto/mosquitto.conf has to be configured and certificates have to be generated and provided correctly, see the README.

The node engine also accepts flags to specify the certificate and key file for MQTT over TLS communication, this is also documented in the cluster_orchestrator README.

Unfortunately the eclipse-mosquitto docker container, the python-paho-mqtt library and the go-paho-mqtt library implement different methods for providing the password to  certificate keyfiles (or none at all) which adds to the complexity of the instructions in the README.

### CODE REVIEW

**Comment by Mjaethers** [comment]
Before this can be merged the cluster_service_manager image that is pulled in the docker compose will have to be updated to incorporate [this](https://github.com/oakestra/oakestra-net/pull/189) PR

**Comment by Mjaethers** [comment]
I can also specify
`image: ghcr.io/oakestra/oakestra-net/cluster-service-manager:alpha-v0.4.302` in the override file. However that should be changed again when oakestra-net is released next

**Review by giobart — APPROVED** [review]
LGTM! The only issue is that we’re migrating this Readme to the wiki. So make sure all the content is there because README.md file will only contain build instructions.

**Comment by Mjaethers** [comment]
Thanks! The wiki is page on MQTT Authentication includes everything documented here.
Would you be able to answer my question on the docker packages? I'm unfamiliar with how this kind of problem is usually solved

**Comment by Mjaethers** [comment]
Then regarding the packages, I updated the override with the custom CSM version to use the one with MQTT auth support. The rest should work as expected after the next release then.

**Comment by giobart** [comment]
After merging the systemd PR we have conflicts in the root.go cobra file. Can you check?

**Comment by Mjaethers** [comment]
Fixed!

**Comment by Mjaethers** [comment]
Let me fix the linter checks

**Comment by giobart** [comment]
I'll test the PR and merge it ASAP

**Comment by giobart** [comment]
@Mjaethers Green light on my side :D awesome!! Feel free to merge when you want!

**Pull request merged**
